---
driver_plugin: vagrant

platforms:
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/boxes/opscode-ubuntu-12.04.box
  run_list:
  - recipe[apt]
- name: canonical-ubuntu-12.04
  driver_config:
    box: canonical-ubuntu-12.04
    box_url: http://cloud-images.ubuntu.com/vagrant/precise/current/precise-server-cloudimg-amd64-vagrant-disk1.box
    require_chef_omnibus: true
  run_list:
  - recipe[apt]

suites:
- name: standard
  run_list:
  - recipe[platform_packages]
  - recipe[orch_app]
  - recipe[dummy_app]
  attributes:
    platform_packages:
      pkgs:
        - name: curl
    orch_app:
      apps:
        - name: app1
          user: vagrant
          port: 8000
          ruby_version: 1.9.3-p392
          processes:
          -
            - all
            - 1
          environment:
          -
            - RAILS_ENV
            - production
